### PR TITLE
feat: Add pre-commit hooks for code formatting, linting

### PR DESCRIPTION
**Pull request by why-arong**
This PR introduces pre-commit hooks to ensure consistent code quality and formatting across the project. The following hooks were added:

1. **Rust Hooks**:
   - `cargo fmt`: Automatically formats Rust code according to the standard style.
   - `cargo clippy`: Lints Rust code to detect potential issues and improve code quality.

2. **General Code Quality Hooks**:
   - `trailing-whitespace`: Removes unnecessary trailing whitespace from files.
   - `end-of-file-fixer`: Ensures that files end with a newline.
   - `check-yaml`: Validates YAML file syntax.
   - `check-added-large-files`: Prevents large files from being accidentally committed to the repository.

3. **Python Hooks**:
   - `ruff`: Lints Python code and automatically fixes style issues.

### CODE REVIEW

**Comment by why-arong** [comment]
Note: After this PR is merged, the contribution guide should be updated to include the new pre-commit hooks. Contributors will need to install and configure the pre-commit hooks locally to ensure proper formatting and linting before making any commits.

**Comment by jopemachine** [comment]
Does code formatting and linting checks also apply to the crate in the binding/python directory, in addition to the root directory?

**Comment by jopemachine** [comment]
Ref: 
- https://pre-commit.com/
- https://pypi.org/project/pre-commit/

Prerequisites:
- Install `pre-commit` using pip on dev environment

**Comment by jopemachine** [comment]
Thanks!

**Pull request merged**
